name: kids_money_lite
description: A simple financial literacy app for kids.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  confetti: ^0.7.0
  flutter_animate: ^4.2.0
  google_fonts: ^5.1.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
